spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/czh
    username: root
    password: 123456
    # session过期时间
  session:
    timeout: 86400
server:
  port: 8081
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
##  global-config:
##    # 全局配置
#    db-config:
##      # 数据库配置
#      id-type: auto
